name: Rust

on:
  push:
    branches: [ main, server-core, pg-db ]
  pull_request:
    branches: [ main, server-core, pg-db ]
    types: [assigned, opened, synchronize, reopened, updated]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build
